import { distance } from "../geometry.js";
import type {
  ChemicalComponent,
  InteractionMetadata,
  InteractionRule,
} from "../types.js";
import { interactionMetadata } from "./metadata.js";

const ELEMENTS = [
  "",
  "H",
  "He",
  "Li",
  "Be",
  "B",
  "C",
  "N",
  "O",
  "F",
  "Ne",
  "Na",
  "Mg",
  "Al",
  "Si",
  "P",
  "S",
  "Cl",
  "Ar",
  "K",
  "Ca",
  "Sc",
  "Ti",
  "V",
  "Cr",
  "Mn",
  "Fe",
  "Co",
  "Ni",
  "Cu",
  "Zn",
  "Ga",
  "Ge",
  "As",
  "Se",
  "Br",
  "Kr",
  "Rb",
  "Sr",
  "Y",
  "Zr",
  "Nb",
  "Mo",
  "Tc",
  "Ru",
  "Rh",
  "Pd",
  "Ag",
  "Cd",
  "In",
  "Sn",
  "Sb",
  "Te",
  "I",
  "Xe",
  "Cs",
  "Ba",
  "La",
  "Ce",
  "Pr",
  "Nd",
  "Pm",
  "Sm",
  "Eu",
  "Gd",
  "Tb",
  "Dy",
  "Ho",
  "Er",
  "Tm",
  "Yb",
  "Lu",
  "Hf",
  "Ta",
  "W",
  "Re",
  "Os",
  "Ir",
  "Pt",
  "Au",
  "Hg",
  "Tl",
  "Pb",
  "Bi",
  "Po",
  "At",
  "Rn",
  "Fr",
  "Ra",
  "Ac",
  "Th",
  "Pa",
  "U",
] as const;

/** ProLIF 2.2.1's default MDAnalysis radii preset. */
export const PROLIF_MDA_VDW_RADII: Readonly<Record<string, number>> = {
  H: 1.1,
  He: 1.4,
  Li: 1.82,
  Be: 1.53,
  B: 1.92,
  C: 1.7,
  N: 1.55,
  O: 1.52,
  F: 1.47,
  Ne: 1.54,
  Na: 2.27,
  Mg: 1.73,
  Al: 1.84,
  Si: 2.1,
  P: 1.8,
  S: 1.8,
  Cl: 1.75,
  Ar: 1.88,
  K: 2.75,
  Ca: 2.31,
  Ni: 1.63,
  Cu: 1.4,
  Zn: 1.39,
  Ga: 1.87,
  Ge: 2.11,
  Se: 1.9,
  Br: 1.85,
  Kr: 2.02,
  Sr: 2.49,
  Pd: 1.63,
  Ag: 1.72,
  Cd: 1.58,
  In: 1.93,
  Sn: 2.17,
  Sb: 2.06,
  Te: 2.06,
  I: 1.98,
  Xe: 2.16,
  Cs: 3.43,
  Ba: 2.68,
  Pt: 1.75,
  Au: 1.66,
  Tl: 1.96,
  Pb: 2.02,
  Bi: 2.07,
  Po: 1.97,
  At: 2.02,
  Rn: 2.2,
  Fr: 3.48,
  Ra: 2.83,
  U: 1.86,
};

/** ProLIF 2.2.1's CSD radii preset, used by implicit H-bond scoring. */
export const PROLIF_CSD_VDW_RADII: Readonly<Record<string, number>> = {
  H: 1.2,
  He: 1.43,
  Li: 2.12,
  Be: 1.98,
  B: 1.91,
  C: 1.77,
  N: 1.66,
  O: 1.5,
  F: 1.46,
  Ne: 1.58,
  Na: 2.5,
  Mg: 2.51,
  Al: 2.25,
  Si: 2.19,
  P: 1.9,
  S: 1.89,
  Cl: 1.82,
  Ar: 1.83,
  K: 2.73,
  Ca: 2.62,
  Sc: 2.58,
  Ti: 2.46,
  V: 2.42,
  Cr: 2.45,
  Mn: 2.45,
  Fe: 2.44,
  Co: 2.4,
  Ni: 2.4,
  Cu: 2.38,
  Zn: 2.39,
  Ga: 2.32,
  Ge: 2.29,
  As: 1.88,
  Se: 1.82,
  Br: 1.86,
  Kr: 2.25,
  Rb: 3.21,
  Sr: 2.84,
  Y: 2.75,
  Zr: 2.52,
  Nb: 2.56,
  Mo: 2.45,
  Tc: 2.44,
  Ru: 2.46,
  Rh: 2.44,
  Pd: 2.15,
  Ag: 2.53,
  Cd: 2.49,
  In: 2.43,
  Sn: 2.42,
  Sb: 2.47,
  Te: 1.99,
  I: 2.04,
  Xe: 2.06,
  Cs: 3.48,
  Ba: 3.03,
  La: 2.98,
  Ce: 2.88,
  Pr: 2.92,
  Nd: 2.95,
  Sm: 2.9,
  Eu: 2.87,
  Gd: 2.83,
  Tb: 2.79,
  Dy: 2.87,
  Ho: 2.81,
  Er: 2.83,
  Tm: 2.79,
  Yb: 2.8,
  Lu: 2.74,
  Hf: 2.63,
  Ta: 2.53,
  W: 2.57,
  Re: 2.49,
  Os: 2.48,
  Ir: 2.41,
  Pt: 2.29,
  Au: 2.32,
  Hg: 2.45,
  Tl: 2.47,
  Pb: 2.6,
  Bi: 2.54,
  Ac: 2.8,
  Th: 2.93,
  Pa: 2.88,
  U: 2.71,
  Np: 2.82,
  Pu: 2.81,
  Am: 2.83,
  Cm: 3.05,
  Bk: 3.4,
  Cf: 3.05,
  Es: 2.7,
};

export function elementSymbol(atomicNumber: number): string {
  const symbol = ELEMENTS[atomicNumber];
  if (symbol === undefined || symbol === "") {
    throw new RangeError(`No element symbol for atomic number ${atomicNumber}`);
  }
  return symbol;
}

export class VdWContact implements InteractionRule {
  readonly name = "VdWContact";

  constructor(
    readonly tolerance = 0,
    readonly radii: Readonly<Record<string, number>> = PROLIF_MDA_VDW_RADII,
  ) {
    if (tolerance < 0) {
      throw new RangeError("VdW tolerance must be non-negative");
    }
  }

  detect(
    ligand: ChemicalComponent,
    protein: ChemicalComponent,
  ): readonly InteractionMetadata[] {
    const output: InteractionMetadata[] = [];
    for (const ligandAtom of ligand.atoms) {
      const ligandElement = elementSymbol(ligandAtom.atomicNumber);
      const ligandRadius = this.radii[ligandElement];
      if (ligandRadius === undefined) {
        throw new RangeError(`No VdW radius for ${ligandElement}`);
      }
      for (const proteinAtom of protein.atoms) {
        const proteinElement = elementSymbol(proteinAtom.atomicNumber);
        const proteinRadius = this.radii[proteinElement];
        if (proteinRadius === undefined) {
          throw new RangeError(`No VdW radius for ${proteinElement}`);
        }
        const separation = distance(ligandAtom.position, proteinAtom.position);
        if (separation > ligandRadius + proteinRadius + this.tolerance) continue;
        output.push(
          interactionMetadata(
            this.name,
            ligand,
            protein,
            [ligandAtom.index],
            [proteinAtom.index],
            separation,
          ),
        );
      }
    }
    return output;
  }
}
