export const PROLIF_COMPATIBILITY = {
  upstream: "ProLIF",
  targetVersion: "2.2.x",
  portVersion: "0.1.0-alpha.0",
  rules: {
    Hydrophobic: "implemented",
    HBAcceptor: "implemented",
    HBDonor: "implemented",
    ImplicitHBAcceptor: "implemented",
    ImplicitHBDonor: "implemented",
    XBAcceptor: "implemented",
    XBDonor: "implemented",
    Cationic: "implemented",
    Anionic: "implemented",
    CationPi: "implemented",
    PiCation: "implemented",
    PiStacking: "implemented",
    MetalDonor: "implemented",
    MetalAcceptor: "implemented",
    VdWContact: "implemented",
  },
} as const;
